name: Docker Build and Deploy

on:
  push:
    branches:
      - placeholder

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
          node-version: "18"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read package version
        id: version
        run: |
          echo "::set-output name=version::$(cat package.json | grep '\"version\"' | cut -d ':' -f 2 | tr -d ',"[[:space:]]')"

      - name: Build Docker image
        run: docker build -t yqcyecong/ios17-clock:${{ steps.version.outputs.version }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push yqcyecong/ios17-clock:${{ steps.version.outputs.version }}

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ $(docker ps -aq --filter name=ios17-clock) ]; then docker rm -f ios17-clock;fi
            docker pull yqcyecong/ios17-clock:${{ needs.build.outputs.version }}
            docker run --name ios17-clock -dp 8080:80 yqcyecong/ios17-clock:${{ needs.build.outputs.version }}
